#cloud-config
---
packages:
  - qemu-guest-agent
runcmd:
  - rc-update add qemu-guest-agent || systemctl enable qemu-guest-agent || true
  - rc-service qemu-guest-agent start || systemctl start qemu-guest-agent || true
  - rc-update add sshd || systemctl enable ssh || systemctl enable sshd || true
