#cloud-config
---
groups:
  - docker
users:
  - default
packages:
  - curl
  - qemu-guest-agent
  - docker
write_files:
  # MOTD welcome message
  - path: /etc/motd
    content: |
      Welcome to your Proxmox cloud-init VM!
      This VM was created with the default cloud-init configuration.
      SSH access is enabled with key-based authentication only.
      For executing commads as root use:
      doas <command>
      doas su
    owner: root:root
    permissions: '0644'
  # SSH configuration to disable password login and root login
  - path: /etc/ssh/sshd_config.d/cloud-init.conf
    content: |
      PasswordAuthentication no
      PermitRootLogin no
      ChallengeResponseAuthentication no
    owner: root:root
    permissions: '0644'
  # Docker daemon configuration to limit log growth
  - path: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "local",
        "log-opts": {
          "max-size": "10m",
          "max-file": "3"
        }
      }
    permissions: '0644'
    owner: root:root
runcmd:
  - |
    PRIMARY_USER=$(getent passwd 1001 | cut -d: -f1)
    if [ -n "$PRIMARY_USER" ]; then
      if ! addgroup "$PRIMARY_USER" docker; then
        logger -t cloud-init "Failed to add $PRIMARY_USER to docker group"
      fi
      logger -t cloud-init "Added user $PRIMARY_USER to docker group"
    else
      logger -t cloud-init "No user with UID 1001 found"
    fi
  - rc-update add qemu-guest-agent || true
  - rc-update add sshd || true
  - rc-update add docker || true
  - reboot
